apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: aj596z6zg-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/aj596z6zg-java-quarkus-gitops